Threshold = 95
DisplayMonitorSources = false
EnableUpdates = true
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.usb-Blue_Microphones_Yeti_X_2045SG00DN58_888-000316110306-00.analog-stereo"
LastUsedOutput = ""
