Threshold = 5
DisplayMonitorSources = false
EnableUpdates = true
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.usb-R__DE_R__DE_PodMic_USB_67940A42-00.mono-fallback"
LastUsedOutput = ""
