#!/usr/bin/env bash

log() {
	printf "%s %s\n" "->" "$1"
}

log "updating all asdf-plugin remotes..."
asdf plugin update --all

log "updating each plugin reference to the latest revision..."
{
	while IFS=' ' read -r plugin version; do
		if [ "$plugin" == "java" ]; then
			echo "$plugin $(asdf latest "$plugin" "adoptopenjdk-11")"
		else
			echo "$plugin $(asdf latest "$plugin")"
		fi
	done <~/.tool-versions
} >~/.tool-versions.new

cp ~/.tool-versions ~/.tool-versions.bk
mv ~/.tool-versions.new ~/.tool-versions

log "old revision versions:"
cat ~/.tool-versions.bk
log "new revision versions:"
cat ~/.tool-versions

while true; do
	read -p "do you wish to install all new revisions? (y/n): " yn
	case $yn in
	[yy]*)
		asdf install
		break
		;;
	[nn]*) exit ;;
	*) log "please answer yes or no." ;;
	esac
done

log "done, bye! 👋"
