#!/usr/bin/env python3

import json
import subprocess
import sys
import time


def check_dependency(command):
    try:
        subprocess.run([command, "--version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except FileNotFoundError:
        print(f"Error: The command '{command}' is not found. Please install it before proceeding.")
        sys.exit(1)


def run_command(command_list, capture_output=True):
    try:
        result = subprocess.run(command_list, capture_output=capture_output, text=True, check=True)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Command failed with error: {e}")
        sys.exit(1)


def prompt():
    ans = input("Continue? (y/n): ")
    if ans != "y":
        print("skipping")
        return False
    return True


def get_instances(ASG_NAME):
    return run_command(
        [
            "aws",
            "autoscaling",
            "describe-auto-scaling-groups",
            "--auto-scaling-group-name",
            ASG_NAME,
            "--query",
            "AutoScalingGroups[].Instances[][InstanceId]",
            "--output",
            "text",
        ]
    ).split()


def get_node_name(instance_id):
    return run_command(
        [
            "aws",
            "ec2",
            "describe-instances",
            "--instance-ids",
            instance_id,
            "--query",
            "Reservations[].Instances[].PrivateDnsName",
            "--output",
            "text",
        ]
    )


def get_node_version(node_name):
    return run_command(
        [
            "kubectl",
            "get",
            "node",
            node_name,
            "-o",
            "custom-columns=VERSION:.status.nodeInfo.kubeletVersion",
            "--no-headers=true",
        ]
    )


def main():
    for cmd in ["aws", "kubectl"]:
        check_dependency(cmd)

    K8S_VERSION = input("Enter the target Kubernetes version (e.g., 1.24): ")
    if not K8S_VERSION:
        print("Error - Kubernetes version not provided.")
        sys.exit(1)

    WAIT = 60
    ASG_NAME = input("Enter the ASG name: ")

    if not ASG_NAME:
        print("Error - ASG name parameter not provided.")
        sys.exit(1)

    instances = get_instances(ASG_NAME)

    for instance in instances:
        node_name = get_node_name(instance)

        run_command(["kubectl", "get", "node", node_name, "--no-headers=true"])

        node_version = get_node_version(node_name)

        if not node_version:
            print("Version is empty. Skipping ...")
            continue

        if K8S_VERSION in node_version:
            print(f"Node {node_name} matches desired version {K8S_VERSION}. Skipping ...")
            continue

        if not prompt():
            continue

        run_command(
            ["kubectl", "drain", "--ignore-daemonsets=true", "--delete-emptydir-data=true", "--force", node_name]
        )

        print(f"Waiting {WAIT} seconds ...")
        time.sleep(WAIT)

        print(f"Checking for pods on node {node_name} ...")

        pod_data = json.loads(run_command(["kubectl", "get", "po", "-A", "-o", "json"]))

        for item in pod_data["items"]:
            if item["spec"]["nodeName"] == node_name:
                print(item["metadata"]["name"])

        print("Deleting node in 10 seconds ... press Ctrl-C to abort")
        time.sleep(10)
        run_command(["kubectl", "delete", "node", node_name])


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nOperation cancelled by the user. Exiting...")
        sys.exit(1)
