#!/usr/bin/env python3

import os
import subprocess

repo_directory = os.path.expanduser("~/Documents/repositories")


def is_git_directory(directory):
    """
    Checks if a directory is a Git repository by looking for a .git subdirectory.
    """
    return os.path.isdir(os.path.join(directory, ".git"))


def get_git_main_branch(directory):
    """
    Determines the name of the main branch for the Git repository located at 'directory'.
    """
    os.chdir(directory)
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"], check=True, capture_output=True, text=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Failed to determine the main branch for {directory}. Error: {str(e)}")
        return None


def git_pull(directory):
    """
    Performs a Git pull operation in the specified directory.
    """
    os.chdir(directory)  # Navigate to directory
    main_branch = get_git_main_branch(directory)

    if main_branch is None:
        print(f"Skipping pull operation for {directory}.")
        return

    try:
        # Run git pull command for the detected main branch
        subprocess.run(["git", "pull", "origin", main_branch], check=True, capture_output=True, text=True)
        print(f"Successfully updated {directory} from '{main_branch}' branch.")
    except subprocess.CalledProcessError as e:
        print(f"Failed to update {directory} from '{main_branch}' branch. Error: {str(e)}")


def main():
    if os.path.exists(repo_directory):
        for root, dirs, _ in os.walk(repo_directory):
            for dir in dirs:
                full_dir_path = os.path.join(root, dir)

                # Skip if the directory is under a .terraform directory
                if ".terraform" in full_dir_path.split("/"):
                    continue

                if is_git_directory(full_dir_path):
                    git_pull(full_dir_path)
    else:
        print(f"The directory {repo_directory} does not exist.")


if __name__ == "__main__":
    main()
