return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        ansible_language_server,
        ansible_lint,
        bash_language_server,
        black,
        dockerfile_language_server,
        goimports,
        golangci_lint,
        golangci_lint_langserver,
        hadolint,
        isort,
        json_lsp,
        lua_language_server,
        markdownlint,
        marksman,
        prittier,
        pyright,
        ruff_lsp,
        shellcheck,
        shfmt,
        stylua,
        terraform_ls,
        tflint,
        yaml_language_server,
      },
    },
  },
}
